### ISSUE TITLE
Crash when building to android device

### ISSUE THREAD

**Issue by patrick-fitzgerald** [richsilv/meteor-cordova-notifications#11]
Hi,
I'm getting the following error when running on an android device. Any ideas on how to fix it?
I'm using Meteor v1.2.0.2.
Thanks

Patricks-MacBook-Air-8:js paddy$  meteor run android-device 
[[[[[ ~/src/test/js ]]]]]               

=> Started proxy.                             

WARNING: You are testing your app on a remote device. For the mobile app to be able to connect to the local server, make sure your device is on the same network, and
         that the network configuration allows clients to talk to each other (no client isolation).
=> Started your app.                          

=> App running at: http://localhost:3000/  
=> Errors executing Cordova commands:         

   While running Cordova app for platform Android with options --device:
   Error: Command failed: /Users/paddy/go/src/test/js/.meteor/local/cordova-build/platforms/android/cordova/run --device
   /Users/paddy/go/src/test/js/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:495: error:
   cannot find symbol
   webView.evaluateJavascript(js, null);
   ^
   symbol:   method evaluateJavascript(String,<null>)
   location: variable webView of type CordovaWebView
   /Users/paddy/go/src/test/js/.meteor/local/cordova-build/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:492: error:
   cannot find symbol
   webView.post(new Runnable(){
   ^
   symbol:   method post(<anonymous Runnable>)
   location: variable webView of type CordovaWebView
   Note: Some input files use or override a deprecated API.
   Note: Recompile with -Xlint:deprecation for details.
   Note: Some input files use unchecked or unsafe operations.
   Note: Recompile with -Xlint:unchecked for details.
   2 errors

   FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileDebugJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  
  /Users/paddy/go/src/test/js/.meteor/local/cordova-build/platforms/android/cordova/node_modules/q/q.js:126
  throw e;
  ^
  Error code 1 for command: /Users/paddy/go/src/test/js/.meteor/local/cordova-build/platforms/android/gradlew with args:
  cdvBuildDebug,-b,/Users/paddy/go/src/test/js/.meteor/local/cordova-build/platforms/android/build.gradle,-PcdvBuildArch=arm,-Dorg.gradle.daemon=true
  at ChildProcess.exitCallback (/tools/utils/processes.js:137:23)
  at ChildProcess.emit (events.js:98:17)
  at Process.ChildProcess._handle.onexit (child_process.js:820:12)

ExitWithCode:1

**Comment by andrea689** [comment]
Hi, I have the same error! :(
I'm using Meteor v1.2.1

**Comment by andrea689** [comment]
I have resolved this and I opened a pull request! :)

**Comment by nabarag** [comment]
Hi , I got the same error while working with meteor 1.2.1. My app is crashing after I include richsilv:cordova-notifications . How to resolve this ? I am trying to incorporate this with meteors todo app .

**Comment by andrea689** [comment]
Hi @nabarag,
until the pull request is not accepted, you can fix it locally.
Download the project and change the file "package.js" [https://github.com/richsilv/meteor-cordova-notifications/pull/12/files](https://github.com/richsilv/meteor-cordova-notifications/pull/12/files)
Then, in your application, create a folder "packages" and insert the project modified.
